### ISSUE TITLE
The error output for darwinia-ethereum bridge when use v0.5.0

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/bridger#419]
```
2022-03-02 04:46:25 ERROR darwinia-ethereum: [darwinia] An error occurred while processing the extrinsics: 
   0: Failed to send query request to subquery: 
      GQLClient Error: Failed to parse response: Error("invalid type: map, expected a string", line: 1, column: 151). The response body is: {"errors":[{"message":"Cannot query field \"outdated\" on type \"ScheduleMMRRootEvent\".","extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"outdated\" on type \"ScheduleMMRRootEvent\".","    at Object.Field (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)","    at Object.enter (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/language/visitor.js:323:29)","    at Object.enter (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/utilities/TypeInfo.js:370:25)","    at visit (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/language/visitor.js:243:26)","    at validate (/usr/local/lib/node_modules/@subql/query/node_modules/graphql/validation/validate.js:69:24)","    at validate (/usr/local/lib/node_modules/@subql/query/node_modules/apollo-server-core/dist/requestPipeline.js:185:39)","    at processGraphQLRequest (/usr/local/lib/node_modules/@subql/query/node_modules/apollo-server-core/dist/requestPipeline.js:90:34)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (node:internal/process/task_queues:96:5)","    at async processHTTPRequest (/usr/local/lib/node_modules/@subql/query/node_modules/apollo-server-core/dist/runHttpQuery.js:187:30)"]}}}]}
```

The reason is to use legacy subql project, but we must use it. because Darwinia chain does not update metadata v14. this should be fixed.

**Comment by fewensa** [comment]
Closed https://github.com/darwinia-network/bridger/pull/420
